name: Raiser
projectReferences:
  Shared:
    path: ../shared/shared.xcodeproj
packages:
  SharedTypes:
    path: ../shared_types/generated/swift/SharedTypes
  HotKey:
    url: "https://github.com/soffes/HotKey"
    majorVersion: "0.2.0"
options:
  bundleIdPrefix: io.stormgate.raiser
attributes:
  BuildIndependentTargetsInParallel: true
targets:
  Raiser:
    type: application
    platform: iOS
    supportedDestinations: [iOS, macOS]
    deploymentTarget: 14.2
    sources:
      - Raiser
      - path: ../shared/src/shared.udl
        buildPhase: sources
    dependencies:
      - target: Shared/uniffi-bindgen-bin
      - target: Shared/shared-staticlib
      - package: SharedTypes
      - package: HotKey
    info:
      path: Raiser/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen: {}
    settings:
      DEVELOPMENT_TEAM: 4R7EAZY462
      PRODUCT_BUNDLE_IDENTIFIER: io.stormgate.raiser
      OTHER_LDFLAGS: [-w]
      SWIFT_OBJC_BRIDGING_HEADER: generated/sharedFFI.h
      ENABLE_USER_SCRIPT_SANDBOXING: NO
    buildRules:
      - name: Generate FFI
        filePattern: "*.udl"
        script: sh -c scripts/generate-ffi.sh
        outputFiles:
          - $(PROJECT_DIR)/generated/$(INPUT_FILE_BASE).swift
          - $(PROJECT_DIR)/generated/$(INPUT_FILE_BASE)FFI.h
        runOncePerArchitecture: false
