return {
	indent_size = 2,
	json_indent_size = 2,
	use_icons = true,
	use_live_diagnostic = false,
	use_noice = true,
	use_haxe = false,
	use_ruby = true,
	use_lua = true,
	use_python = true,
	use_rust = true,
	use_swift = false,
	use_zig = false,
	use_nim = true,
	use_gleam = true,
	use_odin = true,
	use_clang = true,
	use_csharp = false,
	use_go = false,
	use_sql = true,
	use_snyk = false,
	use_wgsl = false,
	theme = require("themes.tokyonight"),
}
