return {
	indent_size = 2,
	json_indent_size = 2,
	use_icons = true,
	use_live_diagnostic = false,
	use_noice = true,
	use_svelte = true,
	use_lua = true,
	use_python = true,
	use_gleam = true,
	use_elixir = true,
	use_clang = true,
	use_go = false,
	use_godot = true,
	theme = require("themes.tokyonight"),
}
