return {
	use_icons = true,
	use_inlay_hints = true,
	use_live_diagnostic = false,
	use_noice = true,
	use_efm = true,
	use_ruby = true,
	use_lua = true,
	use_python = true,
	use_rust = true,
	use_zig = true,
	use_nim = true,
	use_clang = true,
	use_csharp = false,
	use_go = false,
	use_snyk = false,
	use_wgsl = false,
	theme = require("themes.tokyonight"),
}
