- name: Setup essential tools
  hosts: local

  tasks:
    - name: Create sources directory
      file:
        path: "{{item}}"
        state: directory
      with_items:
        - ~/Sources
        - ~/Sources/bin
        - ~/Sources/haxe
        - ~/Projects

    - name: Ensure .config/kitty exists
      file:
        path: ~/.config/kitty
        state: directory

    - name: Copy Geekcaps config
      template:
        src: ./templates/capslock.json
        dest: ~/.config/karabiner/assets/complex_modifications
        force: yes

    - name: Override Kitty conf
      template:
        src: ./templates/kitty.conf
        dest: ~/.config/kitty/kitty.conf
        force: yes

    - name: Copy .zshrc to user's Home
      template:
        src: ./templates/.zshrc
        dest: ~/.zshrc
        force: no

    - name: Install Homebrew
      shell: yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /usr/local/bin/brew

    - name: Install official git
      shell: brew install git
      args:
        creates: /usr/local/bin/git

    - name: Install lazy git
      shell: brew install lazygit
      args:
        creates: /usr/local/bin/lazygit

    - name: Install ripgrep
      shell: brew install ripgrep
      args:
        creates: /usr/local/bin/rg

    - name: Install starship
      shell: brew install starship
      args:
        creates: /usr/local/bin/starship

    - name: Install zoxide
      shell: brew install zoxide
      args:
        creates: /usr/local/bin/zoxide

    - name: Install fzf
      shell: |
        brew install fzf
        $(brew --prefix)/opt/fzf/install
      args:
        creates: /usr/local/bin/fzf

    - name: Install fd
      shell: |
        brew install fd
      args:
        creates: /usr/local/bin/fd

    - name: Install jq
      shell: |
        brew install jq
      args:
        creates: /usr/local/bin/jq

    - name: Install shellcheck
      shell: |
        brew install shellcheck
      args:
        creates: /usr/local/bin/shellcheck

    - name: Install swiftlint
      shell: |
        brew install swiftlint
      args:
        creates: /usr/local/bin/swiftlint

    - name: Install swiftformat
      shell: |
        brew install swiftformat
      args:
        creates: /usr/local/bin/swiftformat
