- name: Setup essential tools
  hosts: local

  tasks:
    - name: Ensure .config/kitty exists
      file:
        path: ~/.config/kitty
        state: directory

    - name: Override Kitty conf
      template:
        src: ./templates/kitty.conf
        dest: ~/.config/kitty/kitty.conf
        force: yes

    - name: Copy .zshrc to user's Home
      template:
        src: ./templates/.zshrc
        dest: ~/.zshrc
        force: no

    - name: Install Homebrew
      shell: yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /opt/homebrew/bin/brew

    - name: Install official git
      shell: brew install git
      args:
        creates: /opt/homebrew/bin/git

    - name: Install lazygit
      shell: brew install lazygit
      args:
        creates: /opt/homebrew/bin/lazygit

    - name: Install ripgrep
      shell: brew install ripgrep
      args:
        creates: /opt/homebrew/bin/rg

    - name: Install zoxide
      shell: brew install zoxide
      args:
        creates: /opt/homebrew/bin/zoxide

    - name: Install fzf
      shell: |
        brew install fzf
        $(brew --prefix)/opt/fzf/install
      args:
        creates: /opt/homebrew/bin/fzf

    - name: Install fd
      shell: |
        brew install fd
      args:
        crates: /opt/homebrew/bin/fd

    - name: Install jq
      shell: |
        brew install jq
      args:
        crates: /opt/homebrew/bin/jq
