- name: Setup essential tools
  hosts: local

  tasks:
    - name: Ensure .config/kitty exists
      file:
        path: ~/.config/kitty
        state: directory

    - name: Override Kitty conf
      template:
        src: ./templates/kitty.conf
        dest: ~/.config/kitty/kitty.conf
        force: yes

    - name: Copy .zshrc to user's Home
      template:
        src: ./templates/.zshrc
        dest: ~/.zshrc
        force: no

    - name: Install Homebrew
      shell: yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /usr/local/bin/brew

    - name: Install official git
      shell: brew install git
      args:
        creates: /usr/local/Cellar/git/

    - name: Install Fzf
      shell: |
        brew install fzf
        $(brew --prefix)/opt/fzf/install
      args:
        creates: /usr/local/bin/fzf

    - name: Install Terraform
      shell: |
        brew tap hashicorp/tap
        brew install hashicorp/tap/terraform
      args:
        creates: /usr/local/bin/terraform
