- name: Setup scripting languages
  hosts: local

  tasks:
    - name: Download nvm installation
      shell: yes | /bin/bash -c "$(curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh)"
      args:
        creates: ~/.nvm/nvm.sh

    - name: Install Node.js latest version
      shell: |
        source ~/.nvm/nvm.sh
        nvm install stable
        nvm use stable
      args:
        executable: /bin/zsh
        creates: ~/.nvm/versions/node

    - name: Install rbenv
      shell: brew install rbenv
      args:
        creates: /opt/homebrew/bin/rbenv

    - name: Install ruby-build
      shell: brew install ruby-build
      args:
        creates: /opt/homebrew/bin/ruby-build

    - name: Install eslint, json, html, css lsp
      shell: npm i -g vscode-langservers-extracted graphql-language-service-cli bash-language-server eslint_d write-good pm2 @metacraft/cli
