- name: Configure fancy NeoVim
  hosts: local

  tasks:
    - name: Create symlink to wezterm configure
      file:
        src: ~/nerdtools/wezterm/
        dest: ~/.config/wezterm
        state: link

    - name: Install NeoVim
      shell: brew install --HEAD neovim
      args:
        creates: /usr/local/bin/nvim

    - name: Create symlink to neovim configure
      file:
        src: ~/nerdtools/nvim/
        dest: ~/.config/nvim
        state: link

    - name: Create .ideavimrc symlink
      template:
        src: ./templates/.ideavimrc
        dest: ~/.ideavimrc
        force: yes
