- name: Configure fancy NeoVim
  hosts: local

  tasks:
    # - name: Install NeoVim
    #   shell: brew install --HEAD neovim
    #   args:
    #     creates: /usr/local/bin/nvim

    - name: Create symlink to neovim configure
      file:
        src: ~/nerdtools/nvim/
        dest: ~/.config/nvim
        state: link

    - name: Create .ideavimrc symlink
      template:
        src: ./templates/.ideavimrc
        dest: ~/.ideavimrc
        force: yes

    - name: Create symlink to Alacritty configure
      file:
        src: ~/nerdtools/conf/alacritty/
        dest: ~/.config/alacritty
        state: link

    - name: Create symlink to Wezterm configure
      file:
        src: ~/nerdtools/conf/wezterm/
        dest: ~/.config/wezterm
        state: link

    - name: Create symlink to Nushell configure
      file:
        src: ~/nerdtools/conf/nushell/
        dest: ~/Libary/Applicaiton Support/nushell
        state: link

    - name: Create revive.toml symlink for Golang
      file:
        src: ~/nerdtools/conf/revive.toml
        dest: ~/revive.toml
        state: link

    - name: Create config.yml symlink for Lazygit
      file:
        src: ~/nerdtools/conf/lazygit.yml
        dest: ~/Library/Application Support/lazygit/config.yml
        state: link

    - name: Create zls.json for Zig
      file:
        src: ~/nerdtools/conf/zls.json
        dest: "~/Library/Application Support/zls.json"
        state: link
