[general]
import = [
  "~/nerdtools/conf/alacritty/themes/tokyo-night.toml",
  "~/nerdtools/conf/alacritty/defaults.toml",
  "~/.config/nerdtools/alacritty.toml",
]

[[keyboard.bindings]]
chars = " w"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\f"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\r"
key = "Return"
mods = "Shift"

[window]
decorations = "full"
