[general]
import = [
  "~/nerdtools/conf/alacritty/themes/tokyo-night.toml",
  "~/.config/nerdtools/alacritty.toml",
]

[font.bold]
family = "Operator Saigon"
style = "Regular"

[font.bold_italic]
family = "Operator Saigon"
style = "Italic"

[font.italic]
family = "Operator Saigon"
style = "Italic"

[font.normal]
family = "Operator Saigon"
style = "Regular"

[font.offset]
x = 1
y = 2

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[window]
decorations = "full"
