[font]
size = 10.8

[terminal.shell]
program = "pwsh.exe"
args = ["-NoLogo"]

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[104;6u"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[106;6u"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[107;6u"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[108;6u"
key = "L"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Return"
mods = "Alt"
