- name: Setup essential tools
  hosts: ec2

  tasks:
    - name: Create sources directory
      file:
        path: "{{item}}"
        state: directory
      with_items:
        - ~/Sources
        - ~/Projects

    - name: Install lazygit
      shell: brew install lazygit
      args:
        creates: /home/linuxbrew/.linuxbrew/bin/lazygit

    - name: Install ripgrep
      shell: brew install ripgrep
      args:
        creates: /home/linuxbrew/.linuxbrew/bin/rg

    - name: Install zoxide
      shell: brew install zoxide
      args:
        creates: /home/linuxbrew/.linuxbrew/bin/zoxide

    - name: Install Fzf
      shell: |
        brew install fzf
        $(brew --prefix)/opt/fzf/install
      args:
        creates: /home/linuxbrew/.linuxbrew/bin/fzf

    - name: Install fd
      shell: brew install fd
      args:
        creates: /home/linuxbrew/.linuxbrew/bin/fd
