- name: Setup essential tools
  hosts: ec2

  tasks:
    - name: Create sources directory
      file:
        path: "{{item}}"
        state: directory
      with_items:
        - ~/Sources
        - ~/Projects
