- name: Setup essential tools
  hosts: ec2
  vars:
    brew_bin: "/home/linuxbrew/.linuxbrew/bin/"

  tasks:
    - name: Create sources directory
      file:
        path: "{{item}}"
        state: directory
      with_items:
        - ~/Sources
        - ~/Projects

    - name: Essential packages
      become: true
      apt:
        state: present
        update_cache: yes
        name:
          - build-essential
          - procps
          - curl
          - ripgrep
          - zoxide
          - file
          - git
          - fzf
          - zsh

    - name: Install Homebrew
      shell: yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /home/linuxbrew/.linuxbrew/bin/brew

    - name: Install Ruby deps
      shell: "{{brew_bin}}/brew install rbenv ruby-build"
      args:
        creates: "{{brew_bin}}/rbenv"

    - name: Install NeoVim
      shell: "{{brew_bin}}/brew install --HEAD neovim"
      args:
        creates: "{{brew_bin}}/nvim"

    - name: Install starship
      shell: "{{brew_bin}}/brew install starship"
      args:
        creates: "{{brew_bin}}/starship"

    - name: Install lazygit
      shell: "{{brew_bin}}/brew install lazygit"
      args:
        creates: "{{brew_bin}}/lazygit"

    - name: Install ripgrep
      shell: "{{brew_bin}}/brew install ripgrep"
      args:
        creates: "{{brew_bin}}/rg"

    - name: Install zoxide
      shell: "{{brew_bin}}/brew install zoxide"
      args:
        creates: "{{brew_bin}}/zoxide"

    - name: Install fd
      shell: "{{brew_bin}}/brew install fd"
      args:
        creates: "{{brew_bin}}/fd"

    - name: Install jq
      shell: "{{brew_bin}}/brew install jq"
      args:
        creates: "{{brew_bin}}/jq"
