- name: Setup essential tools
  hosts: ec2

  tasks:
    - name: Create sources directory
      file:
        path: "{{item}}"
        state: directory
      with_items:
        - ~/Sources
        - ~/Projects

    - name: Clone nerdtools
      git:
        repo: https://github.com/cocrafts/nerdtools.git
        dest: ~/nerdtools
        clone: yes

    - name: Install packages
      become: true
      apt:
        name: build-essential
        state: present

    - name: Install fzf
      become: true
      apt:
        name: fzf
        state: present
