- name: Setup essential tools
  hosts: ec2

  tasks:
    - name: Create sources directory
      file:
        path: "{{item}}"
        state: directory
      with_items:
        - ~/Sources
        - ~/Projects

    - name: Install build-essential
      become: true
      apt:
        name: build-essential
        state: present

    - name: Install fzf
      become: true
      apt:
        name: fzf
        state: present
