- name: Setup essential tools
  hosts: local
  vars:
    brew_bin: "/home/linuxbrew/.linuxbrew/bin/"

  tasks:
    - name: Create sources directory
      file:
        path: "{{item}}"
        state: directory
      with_items:
        - ~/Sources
        - ~/Sources/bin
        - ~/Sources/haxe
        - ~/Projects
        - ~/.config/lazygit

    - name: Essential packages
      become: true
      apt:
        state: present
        update_cache: yes
        name:
          - build-essential
          - flatpak
          - procps
          - python3
          - python3-pip
          - curl
          - ripgrep
          - zoxide
          - file
          - git
          - fzf
          - zsh
          - neovim
          - fd-find
          - jq
          - shellcheck
          - libssl-dev
          - pkg-config
          - libyaml-dev
