- name: Setup scripting languages
  hosts: local
  vars:
    node_version: "18.16.0"

  tasks:
    - name: Download nvm installation
      shell: yes | /bin/bash -c "$(curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh)"
      args:
        creates: ~/.nvm/nvm.sh

    - name: Install Node.js latest version
      shell: |
          source ~/.nvm/nvm.sh
          nvm install {{node_version}}
          nvm alias default {{node_version}}
          nvm use {{node_version}}
      args:
        executable: /usr/bin/zsh
        creates: ~/.nvm/versions/node

    - name: Install npm packages
      shell: |
        node --version
        ~/.nvm/versions/node/v{{node_version}}/bin/npm i -g vscode-langservers-extracted graphql-language-service-cli bash-language-server eslint_d write-good pm2 @metacraft/cli
      args:
        creates: ~/.nvm/versions/node
