- name: Setup golang and dependencies
  hosts: local
  vars:
    go_bin: "~/Sources/go/bin"

  tasks:
    - name: Install Go
      shell: |
        curl -Lo golang.tar.gz "https://go.dev/dl/go1.21.5.linux-arm64.tar.gz"
        tar -C ~/Sources -xvf golang.tar.gz 
      args:
        creates: "{{go_bin}}"

    - name: Install efm-langserver
      shell: "{{go_bin}}/go install github.com/mattn/efm-langserver@latest"
      # args:
      #   creates: "{{brew_bin}}/efm-langserver"
