- name: Setup golang and dependencies
  hosts: local
  vars:
    cargo_bin: "~/.cargo/bin"
    go_version: "1.21.6"
    mise_go: "~/.local/share/mise/installs/go"
    go_bin: "~/go/bin"

  tasks:
    - name: Install Go {{go_version}}
      command: "{{cargo_bin}}/mise use -g go@{{go_version}}"
      args:
        creates: "{{mise_go}}/{{go_version}}/go/bin/go"

    - name: Install efm-langserver
      shell: "{{mise_go}}/{{go_version}}/go/bin/go install github.com/mattn/efm-langserver@latest"
      args:
        creates: "{{mise_go}}/{{go_version}}/packages/bin/efm-langserver"

    - name: Install lazygit
      shell: "{{mise_go}}/{{go_version}}/go/bin/go install github.com/jesseduffield/lazygit@latest"
      args:
        creates: "{{mise_go}}/{{go_version}}/packages/bin/lazygit"
