- name: Setup rust toolchain
  hosts: local
  vars:
    cargo_bin: "~/.cargo/bin"

  tasks:
    - name: check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      ignore_errors: yes

    - name: Download Installer
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: ~/Sources/sh.rustup.rs
        mode: '0755'
        force: 'yes'
      tags:
        - rust

    - name: install rust/cargo
      when: cargo_exists is failed
      shell: ~/Sources/sh.rustup.rs -y
      tags:
        - rust

    - name: Install cargo deps
      shell: "{{cargo_bin}}/cargo install typos-cli neocmakelsp selene"

    - name: Install taplo-cli (for Toml)
      shell: "{{cargo_bin}}/cargo install --features lsp --locked taplo-cli"

    - name: Install wgsl-analyzer 
      shell: "{{cargo_bin}}/cargo install --git https://github.com/wgsl-analyzer/wgsl-analyzer wgsl_analyzer"
