# entry.sh — sourced from ~/.zshrc on every machine.
#
# THIS FILE IS THE CANONICAL CONTRACT.
# It defines what the machine MUST provide for the shell to work correctly:
# tools at specific paths, dirs that exist, env vars, etc.
#
# setup/ contains tested recipes to make a machine satisfy this contract.
# Setup procedures vary per OS; this contract is identical everywhere.
# That's how cross-platform determinism is achieved.
#
# Do NOT edit this file from setup scripts. It is hand-maintained.

# ── Universal env ──────────────────────────────────────────────
export LANG=en_US.UTF-8
export ZSH="$HOME/.oh-my-zsh"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)
export STARSHIP_CONFIG="$HOME/nerdtools/conf/starship.toml"
export REACT_EDITOR=nvim
export EDITOR=nvim
export VISUAL=nvim

# ── PATH (existence-checked) ───────────────────────────────────
for d in \
  "$HOME/Sources/neovim/bin" \
  "$HOME/.local/bin" \
  "$HOME/.cargo/bin" \
  "$HOME/Sources/bin" \
  "$HOME/go/bin" \
  "$HOME/nerdtools/bin"
do
  [[ -d "$d" ]] && PATH="$PATH:$d"
done
export PATH

# ── Brew shellenv (Mac/Linuxbrew) ──────────────────────────────
# brew quyết prefix per-arch — detect, không hardcode
for brew_bin in \
  /opt/homebrew/bin/brew \
  /usr/local/bin/brew \
  /home/linuxbrew/.linuxbrew/bin/brew
do
  [[ -x "$brew_bin" ]] && eval "$($brew_bin shellenv)" && break
done

# ── mise (canonical: ~/.local/bin/mise — see setup/02-mise.md) ─
[[ -x "$HOME/.local/bin/mise" ]] && eval "$($HOME/.local/bin/mise activate zsh)"

# ── oh-my-zsh ──────────────────────────────────────────────────
plugins=(git copyfile jsontools zsh-autosuggestions zsh-syntax-highlighting)
[[ -f "$ZSH/oh-my-zsh.sh" ]] && source "$ZSH/oh-my-zsh.sh"

# ── Aliases ────────────────────────────────────────────────────
alias vide="neovide"
alias nvim="env TERM=wezterm nvim"

# ── Tools post-mise (PATH-discoverable) ────────────────────────
command -v starship >/dev/null && eval "$(starship init zsh)"

# ── LLVM via brew prefix (cross-arch) ──────────────────────────
# brew quyết Cellar location → dùng $HOMEBREW_PREFIX (set bởi shellenv)
[[ -n "$HOMEBREW_PREFIX" && -d "$HOMEBREW_PREFIX/opt/llvm/bin" ]] && \
  PATH="$PATH:$HOMEBREW_PREFIX/opt/llvm/bin"
export PATH

# ── History config ─────────────────────────────────────────────
HISTORY_IGNORE="(clear|ls|cd|pwd|exit|history)"
zshaddhistory() {
  emulate -L zsh
  [[ $1 != ${~HISTORY_IGNORE} ]]
}

# ── Keybindings ────────────────────────────────────────────────
[[ -f "$HOME/nerdtools/zsh/keybindings.sh" ]] && source "$HOME/nerdtools/zsh/keybindings.sh"

# ── Local override (ngoài Syncthing) ───────────────────────────
[[ -f "$HOME/.config/nerdtools/local.zsh" ]] && source "$HOME/.config/nerdtools/local.zsh"
